### ISSUE TITLE
Manual mode changes do not work 

### ISSUE THREAD

**Issue by 149segolte** [svecosystem/mode-watcher#102]
### Describe the bug

In a barebones SvelteKit project with Shadcn-svelte, the mode-watcher toggle does not work.
Project configured using `shadcn-svelte@next`.

- The `<ModeWatcher />` works as expected. (Tested using devtools Rendering tab)
- Using `toggleMode` sets `style="color-scheme: dark;"`, but does not set `class="dark"`
- Using `setMode` does not set anything.

### Reproduction

**Steps to recreate on stackblitz:**
- Create a barebones SvelteKit project or use `pnpm dlx sv create new-app` (Enable typescript and tailwindcss)
- Initialize shadcn-svelte using `pnpm dlx shadcn-svelte@next init`
- Add mode-watcher using `pnpm i mode-watcher`
- Replace `+layout.svelte` with:
```svelte
<script lang="ts">
	import { ModeWatcher, toggleMode } from 'mode-watcher';
	import '../app.css';
	let { children } = $props();
</script>

<!-- <ModeWatcher /> --> <!-- This works -->
<button onclick={toggleMode}>Toggle Mode</button> <!-- This does not work -->
{@render children()}
```

[Stackblitz](https://stackblitz.com/edit/stackblitz-starters-nqyruw?file=src%2Froutes%2F%2Blayout.svelte)

### System Info

```bash
System:
    OS: Linux 6.11 Fedora Linux 41 (KDE Plasma)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 22.28 GB / 31.09 GB
    Container: Yes
    Shell: 5.2.32 - /bin/bash
  Binaries:
    Node: 20.17.0 - ~/.local/share/mise/installs/node/lts/bin/node
    npm: 10.8.2 - ~/.local/share/mise/installs/node/lts/bin/npm
    pnpm: 9.14.2 - ~/.local/share/mise/installs/node/lts/bin/pnpm
    bun: 1.1.29 - ~/.local/share/mise/installs/bun/latest/bin/bun
  Browsers:
    Chrome: 131.0.6778.85
  npmPackages:
    @sveltejs/kit: ^2.0.0 => 2.8.4
    mode-watcher: ^0.5.0 => 0.5.0
    svelte: ^5.0.0 => 5.2.8
```

### Severity

blocking all usage of mode-watcher

**Comment by ollema** [comment]
wait - what do you mean?

you need to include the `<ModeWatcher />` component somewhere in your app, for example in the layout is included in the instructions:

> Add the ModeWatcher component to your root `+layout.svelte` file.
```svelte
<script lang="ts">
	import { ModeWatcher } from "mode-watcher";
</script>

<ModeWatcher />
```

have you done that?

---

I'm confused when you write:

- Replace +layout.svelte with:
```html
<script lang="ts">
	import { ModeWatcher, toggleMode } from 'mode-watcher';
	import '../app.css';
	let { children } = $props();
</script>

<!-- <ModeWatcher /> --> <!-- This works -->
<button onclick={toggleMode}>Toggle Mode</button> <!-- This does not work -->
{@render children()}
```

because `ModeWatcher` is commented out, then it makes sense that it does not work.

but are you saying that:
```html
<script lang="ts">
	import { ModeWatcher, toggleMode } from 'mode-watcher';
	import '../app.css';
	let { children } = $props();
</script>

<ModeWatcher />
<button onclick={toggleMode}>Toggle Mode</button>
{@render children()}
```
also does not work?

please clarify :)
