### ISSUE TITLE
Support for Svelte 5 Runes Mode

### ISSUE THREAD

**Issue by andrewdcato** [svecosystem/mode-watcher#103]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

When trying to upgrade projects to Svelte 5, I get compiler errors because this dependency does not support Runes mode.

```
✘ [ERROR] [project directory]/node_modules/.pnpm/mode-watcher@0.5.0_svelte@5.6.0/node_modules/mode-watcher/dist/mode-watcher.svelte:21:0 Cannot use `export let` in runes mode — use `$props()` instead [plugin vite-plugin-svelte:optimize-svelte]

../../node_modules/.pnpm/mode-watcher@0.5.0_svelte@5.6.0/node_modules/mode-watcher/dist/mode-watcher.svelte:21:0:
       21 │ xport let track = true;
          ╵ ^

The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

     ../../node_modules/.pnpm/mode-watcher@0.5.0_svelte@5.6.0/node_modules/mode-watcher/dist/index.js:3:39:
       3 │ export { default as ModeWatcher } from "./mode-watcher.svelte";

```

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

* [Runes mode announcement](https://svelte.dev/blog/runes)
* [Runes mode docs](https://svelte.dev/docs/svelte/what-are-runes)

**Comment by huntabyte** [comment]
It does support Svelte 5; I'm using it in multiple Svelte 5 projects. However, if you have strict settings on one of your configs, then yeah, of course, it won't work.

There is a plan to update it to Svelte 5 in the near future.

**Comment by huntabyte** [comment]
Going to close this issue as it's not necessary. The team is well aware of a new Svelte major and will have a release when it's ready 😃

**Comment by andrewdcato** [comment]
Is there an ETA?

**Comment by huntabyte** [comment]
ETA is soonish

**Comment by andrewdcato** [comment]
Can you elaborate further on what `soonish` means? 

Are we talking EOY, Q1 2025, etc?
