### ISSUE TITLE
Ability to be integrated into a system that relies on a theme set in the DB

### ISSUE THREAD

**Issue by saturnonearth** [svecosystem/mode-watcher#24]
Would be great if this could able to be integrated into a system that relies on a theme set in the DB instead of default system settings?

My current flow with my own system is:

1. User signs up -> whatever system default they currently have is set as their "theme" setting in their account on the backend.
2. Cookie is set for theme upon log-in in the future.

You wrote on twitter:

> I think that should be possible, maybe via a prop to the component

**Comment by yomp-admin** [comment]
We require this I think it will be very useful

**Comment by huntabyte** [comment]
Hey @saturnonearth & @yomp-admin,

You should be able to accomplish this now using the `defaultMode` prop exposed by the `<ModeWatcher />` component. You'd just have to ensure that the default mode is SSR'd through your load function or whatever, and you'd be responsible for setting the cookie when the user goes to change their mode.
