### ISSUE TITLE
Add option to set theme-color property

### ISSUE THREAD

**Issue by buhodev** [svecosystem/mode-watcher#40]
Hi! I was using this snippet in a PWA to set the [theme-color property](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color) that switches the navbar between theme changes, and I wonder if this could be an addition to this package:

```js
function setThemeColor(darkThemeColor, lightThemeColor) {
  const themeColorEl = document.querySelector('meta[name="theme-color"]')
  if (themeColorEl) themeColorEl.setAttribute('content', $mode === 'dark' ? darkThemeColor : lightThemeColor);
}
```

**Comment by huntabyte** [comment]
Hey @buhodev thanks for raising an issue!

This seems like something that could be worth adding. Is this something you'd like to submit a PR to add?

**Comment by buhodev** [comment]
Sure, what do you think could be a nice API for this? I'm thinking on something like:

```svelte
<ModeWatcher themeColors={{dark: 'black', light: 'white'}} />
```
