### ISSUE TITLE
Add support for color scheme switching through form actions

### ISSUE THREAD

**Issue by jasperkelder** [svecosystem/mode-watcher#70]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

One of SvelteKit’s differentiating features is progressive enhancement through form actions, a functional fallback system for whenever JS, for whatever reason, goes out of the window over at the client side. I think leveraging this system for core functionality makes sense, so I’m wondering whether it might be feasible to facilitate this as an option for mode-watcher?

I’m not sure yet if it could match the elegance of mode-watcher’s JS only implementation, but in my experience it’s definitely feasible to implement something like this one way or another. The general idea of my own current implementation is a use:enhance form with a regular JS button and a noscript element containing buttons with formactions, each extended with their own search parameter, accompanied by logic to hide whichever button should not be applicable. Setting something like this up might be streamlined with a customizable component and an import for the form action.

Would such a concept fit this project?

### What type of pull request would this be?

None

**Comment by huntabyte** [comment]
I think this is something that could easily be handled in user land using the cookie API long with the existing APIs exposed by mode-watcher to accomplish this.
