### ISSUE TITLE
Hydration mismatch with Svelte 5

### ISSUE THREAD

**Issue by eonward** [svecosystem/mode-watcher#71]
### Describe the bug

When using Svelte 5, mode-watcher causes a hydration mismatch -- an incongruency between the UI initially rendered on the server side and the client. Can be bypassed with a browser check, but not ideal.

### Reproduction

- `pnpm create svelte@next` or opt into Svelte 5 during project creation
- Import ModeWatcher and drop it a page or layout

This may throw a ERR_SVELTE_HYDRATION_MISMATCH on the client. I have also gotten a "orphaned $effect rune" error in a more complex codebase

Tested in svelte 5.0.0-next.81
Issue appears to not be consistent

### Logs

```bash
ERR_SVELTE_HYDRATION_MISMATCH: Hydration failed because the initial UI does not match what was rendered on the server. Error: this={...} of <svelte:component> should specify a Svelte component.
    validate_dynamic_component validate.js:38
    Root root.svelte:77
    e svelte-component.js:81
    execute_reaction_fn runtime.js:223
    execute_effect runtime.js:398
```
...
```
    initialize client.js:433
    _hydrate client.js:2385
    start client.js:293
    <anonymous> (index):3536
    (Async: promise callback)
    <anonymous> 
```
```


### System Info

```bash
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    Memory: 9.50 GB / 15.56 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.8.1 - ~/miniconda3/envs/node/bin/node
    npm: 10.5.0 - ~/miniconda3/envs/node/bin/npm
    pnpm: 8.15.5 - ~/miniconda3/envs/node/bin/pnpm
```

### Severity

annoyance

**Comment by huntabyte** [comment]
We aren't supporting Svelte 5 until it is stable.

**Comment by MentalGear** [comment]
with buts ui coming to svelte 5, this issue becomes relevant again !

**Comment by natehouk** [comment]
+1

**Comment by DhruvArora-03** [comment]
+1

**Comment by petewhitfield** [comment]
+1

**Comment by huntabyte** [comment]
Did you all update mode watcher to `@latest`?
