### ISSUE TITLE
Better documentation for DaisyUI

### ISSUE THREAD

**Issue by xl0** [svecosystem/mode-watcher#85]
### Change Type

Addition

### Proposed Changes

The current example https://mode-watcher.svecosystem.com/docs/api-reference/theme updates the local storage but does not update the HTML attribute. Would it be a good idea to include a
```js
rootEl.setAttribute('data-theme', theme);
```
in `setTheme()`?

Alternatively, it would be nice to document it. My current approach (and I'm a beginner when it comes to webdev):
```
	function cycleTheme() {
		toggleMode();
		const rootEl = document.documentElement;
		const theme = $mode === 'dark' ? 'dark' : 'light';
		setTheme(theme);
		rootEl.setAttribute('data-theme', theme);
	}
...
<button on:click={cycleTheme}>Toggle Mode</button>
```

I'm using the "dark:" and "light" daisyui themes. If this is a reasonable way to do this, and if you don't want to add the `setAttreibute()` to `setThemre()`, it would be nice to add it to the docs.

**Comment by huntabyte** [comment]
Hey @xl0, you've actually found a bug rather than a documentation issue.

I'm pushing a patch release now to fix this. The `data-theme` attribute _should_ be syncing. Thanks for bringing this to my attention!

**Comment by sksar** [comment]
@huntabyte this issue still persists. I tried with v0.4.1 did not fix the issue. Had to rollback to v0.3.1 for now.
