### ISSUE TITLE
Docs request: how to safely use the nonce feature?

### ISSUE THREAD

**Issue by fnimick** [svecosystem/mode-watcher#86]
### Change Type

Addition

### Proposed Changes

We shouldn't leave the nonce static (either committed to code or in an environment variable) as a predictable nonce used for both mode-watcher and the CSP will allow bad actors to duplicate the nonce in a script injection attack.

How do you generate a dynamic nonce and provide it to both the CSP and the prop?

**Comment by huntabyte** [comment]
This is outside the scope of this project. We won't be documenting how to securely handle nonces; we just provide an interface for using them with Mode Watcher.

However, you should be able to generate one in your `handle` hook, set it to a value on `event.locals`, `resolve` the page content, create a csp value and apply it to the response headers before returning the response.

**Comment by fnimick** [comment]
I would at least suggest adding a warning around *NOT* using a static nonce, since that is the "obvious" way to do it using the svelte config rather than manually manipulating headers in hooks.
